
  CREATE TABLE "SIC"."QQ_ASSISTANTS" 
   (	"TRANSMISSION_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ASSISTANT_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"EXEC_DATE" DATE, 
	 PRIMARY KEY ("TRANSMISSION_ID", "ASSISTANT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK96678CD457935048" FOREIGN KEY ("ASSISTANT_ID")
	  REFERENCES "SIC"."ADM_USER" ("USER_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK96678CD466CC50F7" FOREIGN KEY ("TRANSMISSION_ID")
	  REFERENCES "SIC"."QQ_TRANSMISSION" ("QUESTION_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SIC"."QQ_ASSISTANTS"."TRANSMISSION_ID" IS 'Идентификатор запроса';
 
   COMMENT ON COLUMN "SIC"."QQ_ASSISTANTS"."ASSISTANT_ID" IS 'Идентификатор соисполнителя';
 
   COMMENT ON COLUMN "SIC"."QQ_ASSISTANTS"."EXEC_DATE" IS 'Дата исполнения';
 
