create or replace FUNCTION QQ_GET_CONTACT 
(
  ADDRESS IN VARCHAR2
, PHONE IN VARCHAR2
) RETURN VARCHAR2 IS 
  RESULT VARCHAR2(255);
BEGIN
  RESULT := NULL;
  if ADDRESS IS NOT NULL THEN
    RESULT := ADDRESS;
  ELSIF PHONE IS NOT NULL  THEN
    RESULT := PHONE;
  end if;
  if LENGTH(RESULT) is NOT NULL THEN 
    if RESULT like ADDRESS and PHONE IS NOT NULL THEN
      RESULT := CONCAT(RESULT, CONCAT(', тел. ', PHONE));
    elsif RESULT like PHONE THEN
      RESULT := CONCAT('тел. ', PHONE);
    end if;
  else
     RESULT := ' ';
  end if;

  return RESULT;
END QQ_GET_CONTACT;
