--------------------------------------------------------
--  File created - вторник-Сентябрь-30-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QQ_APPLICANT
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_APPLICANT" 
   (	"QUESTION_ID" NUMBER(19,0), 
	"APPENDS" VARCHAR2(255 CHAR), 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"ORGANIZATION" VARCHAR2(255 CHAR), 
	"BIRTH_YEAR" NUMBER(4,0), 
	"COUNTRY" VARCHAR2(255 CHAR), 
	"MIDDLE_NAME" VARCHAR2(255 CHAR), 
	"ISSUE_DOC_DATE" DATE, 
	"ISSUE_DOC_NUM" VARCHAR2(255 CHAR), 
	"FIRST_NAME" VARCHAR2(255 CHAR), 
	"FIO_JUR_PERSON" VARCHAR2(255 CHAR), 
	"PHONE" VARCHAR2(255 CHAR), 
	"LAST_NAME" VARCHAR2(255 CHAR), 
	"APPLICANT_CATEGORY_ID" NUMBER(19,0), 
	"APPLICANT_TYPE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."QUESTION_ID" IS 'Идентификатор';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."APPENDS" IS 'Приложения';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."ADDRESS" IS 'Адрес';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."ORGANIZATION" IS 'Название организации (для ЮЛ)';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."BIRTH_YEAR" IS 'Год рождения заявителя';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."COUNTRY" IS 'Страна';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."MIDDLE_NAME" IS 'Отчество заявителя (для ФЛ)';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."ISSUE_DOC_DATE" IS 'Дата исходящего документа';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."ISSUE_DOC_NUM" IS 'Номер исходящего документа';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."FIRST_NAME" IS 'Имя заявителя (для ФЛ)';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."FIO_JUR_PERSON" IS 'ФИО юридического лица (кто подписал исходящий документ)';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."PHONE" IS 'Телефон';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."LAST_NAME" IS 'Фамилия заявителя';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."APPLICANT_CATEGORY_ID" IS 'Категория заявителя';
 
   COMMENT ON COLUMN "SIC"."QQ_APPLICANT"."APPLICANT_TYPE_ID" IS 'Тип заявителя';
--------------------------------------------------------
--  DDL for Table QQ_ATTACHED_FILE
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_ATTACHED_FILE" 
   (	"ATTACHED_FILE_ID" NUMBER(19,0), 
	"FILE_NAME" VARCHAR2(256 CHAR), 
	"FILE_TYPE_ID" NUMBER(19,0), 
	"QUESTION_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_ATTACHED_FILE"."ATTACHED_FILE_ID" IS 'Идентификатор';
 
   COMMENT ON COLUMN "SIC"."QQ_ATTACHED_FILE"."FILE_NAME" IS 'Имя файла';
 
   COMMENT ON COLUMN "SIC"."QQ_ATTACHED_FILE"."FILE_TYPE_ID" IS 'Тип файла';
 
   COMMENT ON COLUMN "SIC"."QQ_ATTACHED_FILE"."QUESTION_ID" IS 'Запрос, чей файл';
--------------------------------------------------------
--  DDL for Table QQ_COORDINATION
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_COORDINATION" 
   (	"COORDINATION_ID" NUMBER(19,0), 
	"STAGE_DATE" DATE, 
	"QUESTION_ID" NUMBER(19,0), 
	"STAGE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_COORDINATION"."COORDINATION_ID" IS 'Идентификатор';
 
   COMMENT ON COLUMN "SIC"."QQ_COORDINATION"."STAGE_DATE" IS 'Дата согласования';
 
   COMMENT ON COLUMN "SIC"."QQ_COORDINATION"."QUESTION_ID" IS 'Запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_COORDINATION"."STAGE_ID" IS 'Этап согласования документа';
--------------------------------------------------------
--  DDL for Table QQ_DELIVERY_ACTION
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_DELIVERY_ACTION" 
   (	"DELIVERY_ACTION_ID" NUMBER(19,0), 
	"DOC_COUNT" NUMBER(19,0), 
	"DOC_TYPE_ID" NUMBER(19,0), 
	"QUESTION_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_DELIVERY_ACTION"."DELIVERY_ACTION_ID" IS 'Идентификатор';
 
   COMMENT ON COLUMN "SIC"."QQ_DELIVERY_ACTION"."DOC_COUNT" IS 'Количество документов';
 
   COMMENT ON COLUMN "SIC"."QQ_DELIVERY_ACTION"."DOC_TYPE_ID" IS 'Тип документа';
 
   COMMENT ON COLUMN "SIC"."QQ_DELIVERY_ACTION"."QUESTION_ID" IS 'Запрос';
--------------------------------------------------------
--  DDL for Table QQ_EXECUTION
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_EXECUTION" 
   (	"QUESTION_ID" NUMBER(19,0), 
	"EXEC_DATE" DATE, 
	"ANSWER_RESULT_ID" NUMBER(19,0), 
	"CATEGORY_COMPLEXITY_ID" NUMBER(19,0), 
	"USAGE_ANSWER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_EXECUTION"."QUESTION_ID" IS 'Запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_EXECUTION"."EXEC_DATE" IS 'Дата исполнения';
 
   COMMENT ON COLUMN "SIC"."QQ_EXECUTION"."ANSWER_RESULT_ID" IS 'Результат ответа';
 
   COMMENT ON COLUMN "SIC"."QQ_EXECUTION"."CATEGORY_COMPLEXITY_ID" IS 'Категория сложности';
 
   COMMENT ON COLUMN "SIC"."QQ_EXECUTION"."USAGE_ANSWER_ID" IS 'Тематика ответа';
--------------------------------------------------------
--  DDL for Table QQ_NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_NOTIFICATION" 
   (	"QUESTION_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NOTIFICATION_DATE" DATE, 
	"DELIVERY_TYPE_ID" NUMBER(19,0), 
	"DOC_TYPE_ID" NUMBER(19,0), 
	"EXECUTOR_ID" NUMBER(19,0), 
	"ISSUE_DATE" DATE, 
	 PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE, 
	 CONSTRAINT "FK2D9D8AA685F4B1F" FOREIGN KEY ("DELIVERY_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE, 
	 CONSTRAINT "FK2D9D8AA946C0A33" FOREIGN KEY ("EXECUTOR_ID")
	  REFERENCES "SIC"."ADM_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK2D9D8AAFF003063" FOREIGN KEY ("DOC_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE, 
	 CONSTRAINT "QQ_NOTIFICATION_FK1" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_QUESTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_NOTIFICATION"."QUESTION_ID" IS 'Запрос, по которому уведомление';
 
   COMMENT ON COLUMN "SIC"."QQ_NOTIFICATION"."NOTIFICATION_DATE" IS 'Дата уведомления';
 
   COMMENT ON COLUMN "SIC"."QQ_NOTIFICATION"."DELIVERY_TYPE_ID" IS 'Способ передачи';
 
   COMMENT ON COLUMN "SIC"."QQ_NOTIFICATION"."DOC_TYPE_ID" IS 'Тип документов';
 
   COMMENT ON COLUMN "SIC"."QQ_NOTIFICATION"."EXECUTOR_ID" IS 'Исполнитель';
 
   COMMENT ON COLUMN "SIC"."QQ_NOTIFICATION"."ISSUE_DATE" IS 'Дата выдачи/отправки документа';
--------------------------------------------------------
--  DDL for Table QQ_QUESTION
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_QUESTION" 
   (	"QUESTION_ID" NUMBER(19,0), 
	"INSERT_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"CONTENT" VARCHAR2(4000 CHAR), 
	"PREFIX_NUM" NUMBER(19, 0), 
	"MOTIVATED_REFUSAL" NUMBER(1,0) DEFAULT 0, 
	"PLANNED_FINISH_DATE" DATE, 
	"REG_DATE" DATE, 
	"OBJECT_MNAME" VARCHAR2(255 CHAR), 
	"OBJECT_FNAME" VARCHAR2(255 CHAR), 
	"OBJECT_LNAME" VARCHAR2(255 CHAR), 
	"OBJECT_BIRTHYEAR" NUMBER(10,0), 
	"INSERT_USER_ID" NUMBER(19,0), 
	"UPDATE_USER_ID" NUMBER(19,0), 
	"ANSWER_FORM_TYPE_ID" NUMBER(19,0), 
	"CREATE_ORG_ID" NUMBER(19,0), 
	"EXEC_ORG_ID" NUMBER(19,0), 
	"LITERA_ID" NUMBER(19,0), 
	"QUESTION_TYPE_ID" NUMBER(19,0), 
	"REGISTRATOR_ID" NUMBER(19,0), 
	"STATUS_ID" NUMBER(19,0), 
	"TRANSFER_TYPE_ID" NUMBER(19,0), 
	"SUFIX_NUM" NUMBER(19, 0), 
    "NOTIFY_STATUS_ID" NUMBER(19,0) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."QUESTION_ID" IS 'Идентификатор';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."INSERT_DATE" IS 'Дата создания';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."UPDATE_DATE" IS 'Дата обновления';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."CONTENT" IS 'Содержимое';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."PREFIX_NUM" IS '№ Входящего документа(префикс. пример номера - 1234/23424)';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."MOTIVATED_REFUSAL" IS 'Мотивированный отказ';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."PLANNED_FINISH_DATE" IS 'Заплонированная дата исполнения';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."REG_DATE" IS 'Дата регистрации';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."OBJECT_MNAME" IS 'Отчество на кого запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."OBJECT_FNAME" IS 'Имя на кого запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."OBJECT_LNAME" IS 'Фамилия на кого запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."OBJECT_BIRTHYEAR" IS 'Год рождения на кого запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."INSERT_USER_ID" IS 'Пользователь, создавший запись';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."UPDATE_USER_ID" IS 'Пользователь, обновивший запись';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."ANSWER_FORM_TYPE_ID" IS 'Форма выдачи ответа';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."CREATE_ORG_ID" IS 'Организация, создавшая запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."EXEC_ORG_ID" IS 'Исполняющая организация';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."LITERA_ID" IS 'Литера';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."QUESTION_TYPE_ID" IS 'Вид запроса';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."REGISTRATOR_ID" IS 'Пользователь, зарегистрировавший запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."STATUS_ID" IS 'Статус запроса';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."TRANSFER_TYPE_ID" IS 'Способ передачи';
 
   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."SUFIX_NUM" IS '№ Входящего документа(суффикс)';

   COMMENT ON COLUMN "SIC"."QQ_QUESTION"."NOTIFY_STATUS_ID" IS 'Статус уведомления';
 
   COMMENT ON TABLE "SIC"."QQ_QUESTION"  IS 'Таблица запросов';
--------------------------------------------------------
--  DDL for Table QQ_SEND_ACTION
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_SEND_ACTION" 
   (	"SEND_ACTION_ID" NUMBER(19,0), 
	"SEND_DATE" DATE, 
	"QUESTION_ID" NUMBER(19,0), 
	"SEND_TYPE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_SEND_ACTION"."SEND_ACTION_ID" IS 'Способ отправки';
 
   COMMENT ON COLUMN "SIC"."QQ_SEND_ACTION"."SEND_DATE" IS 'Дата отправки';
 
   COMMENT ON COLUMN "SIC"."QQ_SEND_ACTION"."QUESTION_ID" IS 'Запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_SEND_ACTION"."SEND_TYPE_ID" IS 'Тип отправки';
--------------------------------------------------------
--  DDL for Table QQ_TRANSMISSION
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_TRANSMISSION" 
   (	"QUESTION_ID" NUMBER(19,0), 
	"CONTROL" NUMBER(1,0) DEFAULT 0, 
	"CONTROL_DATE" DATE, 
	"EXECUTION_DATE" DATE, 
	"RESOLUTION_AUTHOR" VARCHAR2(255 CHAR), 
	"BOSS_EXECUTION_DATE" DATE, 
	"STORAGE_NAME" VARCHAR2(255 CHAR), 
	"EXECUTOR_ID" NUMBER(19,0), 
	"BOSS_EXECUTOR_ID" NUMBER(19,0), 
	"STORAGE_TERRITORY_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."QUESTION_ID" IS 'Запрос, к которму принадлежит передача на исполнение';
 
   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."CONTROL" IS 'Признак установки особого контроля за исполнением документа';
 
   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."CONTROL_DATE" IS 'Контрольная дата исполнения';
 
   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."EXECUTION_DATE" IS 'Дата (по исполнителю)';
 
   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."RESOLUTION_AUTHOR" IS 'Автор резолюции';
 
   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."BOSS_EXECUTION_DATE" IS 'Дата (по ответственному)';
 
   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."STORAGE_NAME" IS 'Название хранилища';
 
   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."EXECUTOR_ID" IS 'Исполнитель';
 
   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."BOSS_EXECUTOR_ID" IS 'Ответсвтенный за исполнение';
 
   COMMENT ON COLUMN "SIC"."QQ_TRANSMISSION"."STORAGE_TERRITORY_ID" IS 'Территория хранилища (адрес)';
--------------------------------------------------------
--  DDL for Table QQ_USED_MATERIAL
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_USED_MATERIAL" 
   (	"USED_MATERIAL_ID" NUMBER(19,0), 
	"FOND_NUMBER" VARCHAR2(255 CHAR), 
	"OPIS_NUMBER" VARCHAR2(255 CHAR), 
	"SERIES_NUMBER" VARCHAR2(255 CHAR), 
	"STORAGE_UNIT_NUMBER" VARCHAR2(255 CHAR), 
	"QUESTION_ID" NUMBER(19,0), 
	"REMARK" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_USED_MATERIAL"."USED_MATERIAL_ID" IS 'Идентификатор';
 
   COMMENT ON COLUMN "SIC"."QQ_USED_MATERIAL"."FOND_NUMBER" IS '№ Фонда';
 
   COMMENT ON COLUMN "SIC"."QQ_USED_MATERIAL"."OPIS_NUMBER" IS '№ Описи';
 
   COMMENT ON COLUMN "SIC"."QQ_USED_MATERIAL"."SERIES_NUMBER" IS '№ Листов';
 
   COMMENT ON COLUMN "SIC"."QQ_USED_MATERIAL"."STORAGE_UNIT_NUMBER" IS '№ Единицы хранения';
 
   COMMENT ON COLUMN "SIC"."QQ_USED_MATERIAL"."QUESTION_ID" IS 'Запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_USED_MATERIAL"."REMARK" IS 'Примечание';
--------------------------------------------------------
--  DDL for Table QQ_WAY_TO_SEND
--------------------------------------------------------

  CREATE TABLE "SIC"."QQ_WAY_TO_SEND" 
   (	"QUESTION_ID" NUMBER(19,0), 
	"REMARK" VARCHAR2(255 CHAR), 
	"ISSUE_NUMBER" VARCHAR2(255 CHAR), 
	"RENEWAL_NOTICE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
 

   COMMENT ON COLUMN "SIC"."QQ_WAY_TO_SEND"."QUESTION_ID" IS 'Запрос';
 
   COMMENT ON COLUMN "SIC"."QQ_WAY_TO_SEND"."REMARK" IS 'Примечание';
 
   COMMENT ON COLUMN "SIC"."QQ_WAY_TO_SEND"."ISSUE_NUMBER" IS 'Исходящий номер';
 
   COMMENT ON COLUMN "SIC"."QQ_WAY_TO_SEND"."RENEWAL_NOTICE" IS 'Уведомление о продлении сроков';
--------------------------------------------------------
--  DDL for Index SYS_C00175263
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175263" ON "SIC"."QQ_APPLICANT" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175267
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175267" ON "SIC"."QQ_ATTACHED_FILE" ("ATTACHED_FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index QQ_ATTACHED_FILE_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."QQ_ATTACHED_FILE_INDEX1" ON "SIC"."QQ_ATTACHED_FILE" ("FILE_NAME", "QUESTION_ID", "FILE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175269
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175269" ON "SIC"."QQ_COORDINATION" ("COORDINATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175272
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175272" ON "SIC"."QQ_DELIVERY_ACTION" ("DELIVERY_ACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175274
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175274" ON "SIC"."QQ_EXECUTION" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175280
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175280" ON "SIC"."QQ_NOTIFICATION" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175286
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175286" ON "SIC"."QQ_QUESTION" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175290
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175290" ON "SIC"."QQ_SEND_ACTION" ("SEND_ACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175293
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175293" ON "SIC"."QQ_TRANSMISSION" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175296
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175296" ON "SIC"."QQ_USED_MATERIAL" ("USED_MATERIAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00175299
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIC"."SYS_C00175299" ON "SIC"."QQ_WAY_TO_SEND" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA" ;
--------------------------------------------------------
--  Constraints for Table QQ_APPLICANT
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_APPLICANT" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_APPLICANT" ADD PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QQ_ATTACHED_FILE
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_ATTACHED_FILE" MODIFY ("ATTACHED_FILE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_ATTACHED_FILE" MODIFY ("FILE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_ATTACHED_FILE" MODIFY ("FILE_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_ATTACHED_FILE" ADD PRIMARY KEY ("ATTACHED_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
 
  ALTER TABLE "SIC"."QQ_ATTACHED_FILE" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QQ_COORDINATION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_COORDINATION" MODIFY ("COORDINATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_COORDINATION" ADD PRIMARY KEY ("COORDINATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QQ_DELIVERY_ACTION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_DELIVERY_ACTION" MODIFY ("DELIVERY_ACTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_DELIVERY_ACTION" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_DELIVERY_ACTION" ADD PRIMARY KEY ("DELIVERY_ACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
 
  ALTER TABLE "SIC"."QQ_DELIVERY_ACTION" MODIFY ("DOC_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_DELIVERY_ACTION" MODIFY ("DOC_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QQ_EXECUTION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_EXECUTION" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_EXECUTION" ADD PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QQ_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_NOTIFICATION" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_NOTIFICATION" ADD PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QQ_QUESTION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_QUESTION" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_QUESTION" MODIFY ("INSERT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_QUESTION" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_QUESTION" MODIFY ("INSERT_USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_QUESTION" MODIFY ("UPDATE_USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QQ_SEND_ACTION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_SEND_ACTION" MODIFY ("SEND_ACTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_SEND_ACTION" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_SEND_ACTION" ADD PRIMARY KEY ("SEND_ACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QQ_TRANSMISSION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_TRANSMISSION" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_TRANSMISSION" ADD PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QQ_USED_MATERIAL
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_USED_MATERIAL" MODIFY ("USED_MATERIAL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_USED_MATERIAL" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_USED_MATERIAL" ADD PRIMARY KEY ("USED_MATERIAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QQ_WAY_TO_SEND
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_WAY_TO_SEND" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIC"."QQ_WAY_TO_SEND" ADD PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIC_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_APPLICANT
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_APPLICANT" ADD CONSTRAINT "FKD854F530CBC2602D" FOREIGN KEY ("APPLICANT_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_APPLICANT" ADD CONSTRAINT "FKD854F530F2F69269" FOREIGN KEY ("APPLICANT_CATEGORY_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_APPLICANT" ADD CONSTRAINT "QQ_APPLICANT_FK1" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_QUESTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_ATTACHED_FILE
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_ATTACHED_FILE" ADD CONSTRAINT "FK8F9BF5843EC1CA7" FOREIGN KEY ("FILE_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_ATTACHED_FILE" ADD CONSTRAINT "FK8F9BF58CEAC3022" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_QUESTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_COORDINATION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_COORDINATION" ADD CONSTRAINT "FK39E5E7C877FC226" FOREIGN KEY ("STAGE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_COORDINATION" ADD CONSTRAINT "FK39E5E7CCEAC3022" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_EXECUTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_DELIVERY_ACTION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_DELIVERY_ACTION" ADD CONSTRAINT "FK80C5E8C2CEAC3022" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_EXECUTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "SIC"."QQ_DELIVERY_ACTION" ADD CONSTRAINT "FK80C5E8C2FF003063" FOREIGN KEY ("DOC_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_EXECUTION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_EXECUTION" ADD CONSTRAINT "FK8496EBB93575D966" FOREIGN KEY ("ANSWER_RESULT_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_EXECUTION" ADD CONSTRAINT "FK8496EBB9419B048" FOREIGN KEY ("USAGE_ANSWER_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_EXECUTION" ADD CONSTRAINT "FK8496EBB9D2CCE9A5" FOREIGN KEY ("CATEGORY_COMPLEXITY_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_EXECUTION" ADD CONSTRAINT "QQ_EXECUTION_FK1" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_QUESTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_NOTIFICATION" ADD CONSTRAINT "FK2D9D8AA685F4B1F" FOREIGN KEY ("DELIVERY_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_NOTIFICATION" ADD CONSTRAINT "FK2D9D8AA946C0A33" FOREIGN KEY ("EXECUTOR_ID")
	  REFERENCES "SIC"."ADM_USER" ("USER_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_NOTIFICATION" ADD CONSTRAINT "FK2D9D8AAFF003063" FOREIGN KEY ("DOC_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_NOTIFICATION" ADD CONSTRAINT "QQ_NOTIFICATION_FK1" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_QUESTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_QUESTION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D45432523739AD0" FOREIGN KEY ("ANSWER_FORM_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D45432563019AC5" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SIC"."ADM_USER" ("USER_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D4543257E0134B5" FOREIGN KEY ("INSERT_USER_ID")
	  REFERENCES "SIC"."ADM_USER" ("USER_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D4543258DB60394" FOREIGN KEY ("REGISTRATOR_ID")
	  REFERENCES "SIC"."ADM_USER" ("USER_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D454325A6EE5911" FOREIGN KEY ("QUESTION_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D454325BE4020B2" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D454325C1A40D23" FOREIGN KEY ("CREATE_ORG_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D454325C746A0AA" FOREIGN KEY ("EXEC_ORG_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D454325CFF6967" FOREIGN KEY ("LITERA_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "FK4D454325DDF0016" FOREIGN KEY ("TRANSFER_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;

  ALTER TABLE "SIC"."QQ_QUESTION" ADD CONSTRAINT "QQ_QUESTION_FK1" FOREIGN KEY ("NOTIFY_STATUS_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_SEND_ACTION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_SEND_ACTION" ADD CONSTRAINT "FKAF5ADF2ECEAC3022" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_EXECUTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "SIC"."QQ_SEND_ACTION" ADD CONSTRAINT "QQ_SEND_ACTION_FK1" FOREIGN KEY ("SEND_TYPE_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_TRANSMISSION
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_TRANSMISSION" ADD CONSTRAINT "FK420B23303F9D7ECE" FOREIGN KEY ("STORAGE_TERRITORY_ID")
	  REFERENCES "SIC"."DESCRIPTOR_VALUE" ("DESCRIPTOR_VALUE_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_TRANSMISSION" ADD CONSTRAINT "FK420B233066A715CE" FOREIGN KEY ("EXECUTOR_ID")
	  REFERENCES "SIC"."ADM_USER" ("USER_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_TRANSMISSION" ADD CONSTRAINT "FK420B23309358EA31" FOREIGN KEY ("BOSS_EXECUTOR_ID")
	  REFERENCES "SIC"."ADM_USER" ("USER_ID") ENABLE;
 
  ALTER TABLE "SIC"."QQ_TRANSMISSION" ADD CONSTRAINT "QQ_TRANSMISSIONS_FK1" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_QUESTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_USED_MATERIAL
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_USED_MATERIAL" ADD CONSTRAINT "FKC55D378ACEAC3022" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_EXECUTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QQ_WAY_TO_SEND
--------------------------------------------------------

  ALTER TABLE "SIC"."QQ_WAY_TO_SEND" ADD CONSTRAINT "QQ_WAY_TO_SEND_FK1" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SIC"."QQ_EXECUTION" ("QUESTION_ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  File created - вторник-Сентябрь-30-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_APPLICANTS
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_APPLICANTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_ATTACHED_FILE
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_ATTACHED_FILE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_COORDINATION
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_COORDINATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_DELIVERY_ACTION
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_DELIVERY_ACTION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_EXECUTION
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_EXECUTION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_NOTIFICATION
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_NOTIFICATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_QUESTION
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_QUESTION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_SEND_ACTION
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_SEND_ACTION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_TRANSMISSIONS
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_TRANSMISSIONS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_USED_MATERIAL
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_USED_MATERIAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QQ_WAY_TO_SEND
--------------------------------------------------------

   CREATE SEQUENCE  "SIC"."SEQ_QQ_WAY_TO_SEND"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE FORCE VIEW "SIC"."V_DESC_ATTR_VALUE" ("DESCRIPTOR_VALUE_ATTR_ID", "DESCRIPTOR_VALUE_ID", "ATTR_CODE", "IS_COLLECTION", "ATTR_VALUE") AS 
  (
 SELECT dva.descriptor_value_attr_id, dva.descriptor_value_id, dga.attr_code, dga.is_collection, COALESCE(dva.attr_value, dv.value_code) AS attr_value
   FROM descriptor_value_attr dva
   JOIN descriptor_group_attr dga ON dva.descriptor_group_attr_id = dga.descriptor_group_attr_id
   LEFT JOIN descriptor_value dv ON dva.ref_descriptor_value_id = dv.descriptor_value_id
);


  CREATE OR REPLACE FORCE VIEW "SIC"."V_ADM_USER_RULE" ("USER_ID", "LOGIN", "IS_BLOCKED", "DISPLAYED_NAME", "RULE_CODE") AS 
  SELECT DISTINCT au.user_id,
         au.login,
         au.is_blocked,
         au.displayed_name,
         aar.rule_code
  FROM adm_user au
       JOIN adm_user_group aug ON au.user_id = aug.user_id
       JOIN adm_group_rule agr ON aug.group_id = agr.group_id
       JOIN adm_access_rule aar ON agr.access_rule_id = aar.access_rule_id;

exit;


