Insert into SIC.ADM_EMPLOYEE (EMPLOYEE_ID,USER_ID,DEPARTMENT_ID,POSITION_ID,LAST_NAME,FIRST_NAME,MIDDLE_NAME) values ('41','141','86','209','Благодатских','Сергей','Александрович');
Insert into SIC.ADM_EMPLOYEE (EMPLOYEE_ID,USER_ID,DEPARTMENT_ID,POSITION_ID,LAST_NAME,FIRST_NAME,MIDDLE_NAME) values ('61','161','86','210','Шаповалова','Ярославна','Юрьевна');

Insert into SIC.ADM_USER (USER_ID,USER_TYPE_ID,LOGIN,PASSWORD,IS_BLOCKED,DISPLAYED_NAME) values ('141','82','ARCHIVE_USER','0B5E77B45B9FEA36DF04127C869CB852','0','Благодатских С. А.');
Insert into SIC.ADM_USER (USER_ID,USER_TYPE_ID,LOGIN,PASSWORD,IS_BLOCKED,DISPLAYED_NAME) values ('161','82','SHAP','F7968361B24E2189C636BF03A51AB926','0','Шаповалова Я. Ю.');
Insert into SIC.ADM_USER_GROUP (USER_ID,GROUP_ID) values ('141','101');
Insert into SIC.ADM_USER_GROUP (USER_ID,GROUP_ID) values ('141','102');
Insert into SIC.ADM_USER_GROUP (USER_ID,GROUP_ID) values ('141','103');
Insert into SIC.ADM_USER_GROUP (USER_ID,GROUP_ID) values ('161','101');
Insert into SIC.ADM_USER_GROUP (USER_ID,GROUP_ID) values ('161','102');
Insert into SIC.ADM_USER_GROUP (USER_ID,GROUP_ID) values ('161','103');

