--------------------------------------------------------
--  File created - пятница-Январь-30-2015   
--------------------------------------------------------
REM INSERTING into DESCRIPTOR_GROUP_ATTR
SET DEFINE OFF;
Insert into DESCRIPTOR_GROUP_ATTR (DESCRIPTOR_GROUP_ATTR_ID,DESCRIPTOR_GROUP_ID,DATATYPE_CODE,ATTR_NAME,ATTR_CODE,SORT_ORDER,IS_COLLECTION,IS_REQUIRED,REF_DESCRIPTOR_GROUP_ID) values ('41','103','DESCRIPTOR','Тип элемента организационной структуры','ORG_STRUCTURE_TYPE','1','0','1','102');
Insert into DESCRIPTOR_GROUP_ATTR (DESCRIPTOR_GROUP_ATTR_ID,DESCRIPTOR_GROUP_ID,DATATYPE_CODE,ATTR_NAME,ATTR_CODE,SORT_ORDER,IS_COLLECTION,IS_REQUIRED,REF_DESCRIPTOR_GROUP_ID) values ('61','122','TEXT','Название этапа','stage_name','1','0','1',null);
Insert into DESCRIPTOR_GROUP_ATTR (DESCRIPTOR_GROUP_ATTR_ID,DESCRIPTOR_GROUP_ID,DATATYPE_CODE,ATTR_NAME,ATTR_CODE,SORT_ORDER,IS_COLLECTION,IS_REQUIRED,REF_DESCRIPTOR_GROUP_ID) values ('62','122','TEXT','Исполнитель этапа','stage_executor','1','0','1',null);
Insert into DESCRIPTOR_GROUP_ATTR (DESCRIPTOR_GROUP_ATTR_ID,DESCRIPTOR_GROUP_ID,DATATYPE_CODE,ATTR_NAME,ATTR_CODE,SORT_ORDER,IS_COLLECTION,IS_REQUIRED,REF_DESCRIPTOR_GROUP_ID) values ('63','101','BOOLEAN','Возможность создания через режим администратора','CREATABLE_BY_ADMIN','1','0','1',null);
Insert into DESCRIPTOR_GROUP_ATTR (DESCRIPTOR_GROUP_ATTR_ID,DESCRIPTOR_GROUP_ID,DATATYPE_CODE,ATTR_NAME,ATTR_CODE,SORT_ORDER,IS_COLLECTION,IS_REQUIRED,REF_DESCRIPTOR_GROUP_ID) values ('81','103','TEXT','Адрес','ORG_ADDRESS','3','0','0',null);
Insert into DESCRIPTOR_GROUP_ATTR (DESCRIPTOR_GROUP_ATTR_ID,DESCRIPTOR_GROUP_ID,DATATYPE_CODE,ATTR_NAME,ATTR_CODE,SORT_ORDER,IS_COLLECTION,IS_REQUIRED,REF_DESCRIPTOR_GROUP_ID) values ('64','103','TEXT','Литера','MEMBER_LETTER','0','0','0',null);
