  CREATE OR REPLACE FORCE VIEW "SIC"."V_STRG_ORG_FOR_SEARCH" ("ORG_NAME_ID", "ORGANIZATION_ID", "FULL_NAME", "ARCHIVE_ID", "NOTES", "ARCHIVE_NAME", "FUND_NUM", "PREFIX", "SUFFIX", "FUND_NUMBER_FULL") AS 
  select SON.ORG_NAME_ID, SO.ORGANIZATION_ID, SON.FULL_NAME, SO.ARCHIVE_ID, SO.NOTES,
       DV.FULL_VALUE as ARCHIVE_NAME, SF.FUND_NUM, SF.PREFIX, SF.SUFFIX,
       STORAGE_PACK.GET_FUND_FULL_NUMBER(SF.FUND_NUM, SF.PREFIX, SF.SUFFIX) as FUND_NUMBER_FULL
  from STRG_ORGANIZATION SO
 inner join STRG_ORG_NAME SON
         on SO.ORGANIZATION_ID = SON.ORGANIZATION_ID
        and SON.SORT_ORDER     = 1
 inner join DESCRIPTOR_VALUE DV
         on SO.ARCHIVE_ID = DV.DESCRIPTOR_VALUE_ID
  left join STRG_FUND SF
         on SO.FUND_ID = SF.FUND_ID;

exit;
 
